spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
rules_v1.xlsx
Name	Description
Rule 1	Description 1
Rule 2	Description 2
rules_v2.xlsx
Name	Description
Rule 3	Description 3
Rule 4	Description 4