server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
logging:
  level:
    org.flywaydb: DEBUG
  root: DEBUG
